## Matrix 
$
\begin{bmatrix}
a_{00} & a_{01} & a_{02} \\
a_{10} & a_{11} & a_{12} \\
a_{20} & a_{21} & a_{22}
\end{bmatrix}
$

## Creating a matrix

In [6]:
from numpy import *
a=array([[1, 2], [3, 4]],float)
b=array([[3,1], [5,6]],float)
print(a,",")
print(b)

[[1. 2.]
 [3. 4.]] ,
[[3. 1.]
 [5. 6.]]


## Matrix addition

In [7]:
c=a+b
print(c)

[[ 4.  3.]
 [ 8. 10.]]


## Matrix subtraction 

In [8]:
d=b-a
print(d)

[[ 2. -1.]
 [ 2.  2.]]


## Matrix multiplication 

In [9]:
e=dot(a,b) # dot function to multipy matrices
print(e)

[[13. 13.]
 [29. 27.]]


## Scalar matrix multiplication

In [10]:
f=2*a # multiplying matrix a with 2 
print(f)

[[2. 4.]
 [6. 8.]]


## Matrix Transpose

In [11]:
# Matrix transposition
G=a.T
print(G)

[[1. 3.]
 [2. 4.]]


## Inverse of a matrix
- Here we will use linalg.inv() , function to invert a matrix.
<div class="alert alert-block alert-danger">
<b>Note:</b> It can only be used for square matices.If you want to find inverse of a non square matrix use "linalg.pinv()" method.
</div>


In [12]:
A=array([[2,-3,5], [6,0,4], [1,5,-7]])
H=linalg.inv(A)
print(H)

[[ 0.71428571 -0.14285714  0.42857143]
 [-1.64285714  0.67857143 -0.78571429]
 [-1.07142857  0.46428571 -0.64285714]]


## Determinant 

In [13]:
det=linalg.det(A)
print(A,det)

[[ 2 -3  5]
 [ 6  0  4]
 [ 1  5 -7]] -28.00000000000002


## Inverse Matrix method of solving equation
 
$a_{1}x+b_{1}y+c_{1}z=d1$

$a_{2}x+b_{2}y+c_{2}z=d2$

$a_{3}x+b_{3}y+c_{3}z=d3$

    
$A=
\begin{bmatrix}
a_{1} & b_{1} & c_{1} \\
a_{2} & b_{2} & c_{2} \\
a_{3} & b_{3} & c_{3}
\end{bmatrix}$,
$X=
\begin{bmatrix}
x \\
y \\
z
\end{bmatrix}$,
$B=
\begin{bmatrix}
d_{1} \\
d_{2}\\
d_{3}
\end{bmatrix}$

We can represent the above equations in the form 

$\begin{bmatrix}
a_{1} & b_{1} & c_{1} \\
a_{2} & b_{2} & c_{2} \\
a_{3} & b_{3} & c_{3}
\end{bmatrix}$
$\begin{bmatrix}
x \\
y \\
z
\end{bmatrix}=
\begin{bmatrix}
d_{1} \\
d_{2}\\
d_{3}
\end{bmatrix}$


$AX=B$


$X=A^{-1}B$



Q1.Solve following equations using inverse matrix method.
   - $2x+5y=1$
   - $3x+2y=7$

In [14]:
A=array([[2,5],[3,2]]) 
B=array([[1],[7]])
inv_A=linalg.inv(A) # taking inverse of A
solution=dot(inv_A,B) # multiplying A inverse and B
print(solution)

[[ 3.]
 [-1.]]


Q1.Solve following equations using inverse matrix method.
   - $2x+y+z=10$
   - $3x+2y+3z=18$
   - $x+4y+9z=16$
   
### Solution 
$x=7$,
$y=-9$,
$z=5$

In [15]:
a=array([[2,1,1],[3,2,3],[1,4,9]])
b=array([[10],[18],[16]])
inv_a=linalg.inv(a) # taking inverse of A
solution=dot(inv_a,b) # multiplying A inverse and B
print(solution)

[[ 7.]
 [-9.]
 [ 5.]]


## Guass Elimination 
In this method we convert our matrix into upper triangular matrix using some operations and use back substitution method to compute values of variables.

$
\begin{bmatrix}
a_{00} & a_{01} & a_{02} & \big| & b_{0} \\
a_{10} & a_{11} & a_{12} & \big| & b_{1} \\
a_{20} & a_{21} & a_{22} & \big| & b_{2}
\end{bmatrix}
$
$-->
\begin{bmatrix}
1 & a_{01} & a_{02} & \big| & b_{0} \\
0 & 1 & a_{12} & \big| & b_{1} \\
0 & 0 & a_{22} & \big| & b_{2}
\end{bmatrix}
$


$a_{00}x_{0}+a_{01}x_{1}+a_{02}x_{2}=b_{0}--> R_{1}/a_{00}  $

$a_{10}x_{0}+a_{11}x_{1}+a_{12}x_{2}=b_{1}--> R_{2}-a_{10}R1 |  R_{2}/a_{11} $

$a_{20}x_{0}+a_{21}x_{1}+a_{22}x_{2}=b_{2}--> R_{3}-a_{20}R1 |  R_{3}-a_{21}R_{2}$



Q1.Solve the system of equations using gauss elimniation method

$2x+y+z=10$

$3x+2y+3z=18$

$x+4y+9z=16$


In [38]:
a=array([[2,3,4],[3,4,3],[2,4,9]],float) 
b=array([[10],[18],[16]],float)
n=len(b) #n=3 
print("a is")
print(a)
for i in range(0,n-1):#i=0,1
    m1=a[i,i] 
    print("m1 is",m1)
    a[i,:]=a[i,:]/m1
    b[i]=b[i]/m1
    print(a,",")
    for j in range(i+1,n):#j=2
        m2=a[j,i]
        print("m2 is",m2)
        a[j,:]=a[j,:]-m2*a[i,:]
        b[j]=b[j]-m2*b[i]
        print(a,",")
print("Matrix after gaussian elimination is")
print(a)

a is
[[2. 3. 4.]
 [3. 4. 3.]
 [2. 4. 9.]]
m1 is 2.0
[[1.  1.5 2. ]
 [3.  4.  3. ]
 [2.  4.  9. ]] ,
m2 is 3.0
[[ 1.   1.5  2. ]
 [ 0.  -0.5 -3. ]
 [ 2.   4.   9. ]] ,
m2 is 2.0
[[ 1.   1.5  2. ]
 [ 0.  -0.5 -3. ]
 [ 0.   1.   5. ]] ,
m1 is -0.5
[[ 1.   1.5  2. ]
 [-0.   1.   6. ]
 [ 0.   1.   5. ]] ,
m2 is 1.0
[[ 1.   1.5  2. ]
 [-0.   1.   6. ]
 [ 0.   0.  -1. ]] ,
Matrix after gaussian elimination is
[[ 1.   1.5  2. ]
 [-0.   1.   6. ]
 [ 0.   0.  -1. ]]


In [39]:
b

array([[ 5.],
       [-6.],
       [12.]])

## Back substitution 

In back substitution method, we substitute values of variables from last row,that's why it is called back substitution.

$
\begin{bmatrix}
1 & 0.5 & 0.5 & \big| & 5 \\
0 & 1 & 3 & \big| & 6 \\
0 & 0 & -2 & \big| & -10
\end{bmatrix}
$


This is the formula we are using here

$x_{0}=(b_{0}-a_{01}x_{1}-a_{02}x_{2})/a_{00}$

$x_{1}=(b_{1}-a_{12}x_{2})/a_{11}$

$x_{2}=b_{2}/a_{22}$

 
$$x_i = \frac{{b_i - \sum_{{j=i+1}}^n{{a_{{ij}}  x_j}}}}{{a_{{ii}}}}$$



In [40]:
n = len(b)  # n=3
x = zeros(n) # it creates an array [[0,0,0]]
print(x)
for i in range(n-1,-1,-1): # i=2,1,0
    x[i] = b[i]
    print(x,",")
    # summation process starts
    for j in range(i+1, n):#j=1 won't run ,j=2,j=1,2 
        x[i]=x[i]-a[i, j] * x[j]
    x[i] =x[i]/a[i, i] 
    print(x,",")

print("Solution Vector x:")
print(x)

[0. 0. 0.]
[ 0.  0. 12.] ,
[  0.   0. -12.] ,
[  0.  -6. -12.] ,
[  0.  66. -12.] ,
[  5.  66. -12.] ,
[-70.  66. -12.] ,
Solution Vector x:
[-70.  66. -12.]
