# Matrix
$
\begin{bmatrix}
a_{00} & a_{01} & a_{02} \\
a_{10} & a_{11} & a_{12} \\
a_{20} & a_{21} & a_{22}
\end{bmatrix}
$
## Guass Jordan Elimination 
In this method we convert our matrix into identity matrix using some operations and compute values of variables from b matrix.

$
\begin{bmatrix}
a_{00} & a_{01} & a_{02} & \big| & b_{0} \\
a_{10} & a_{11} & a_{12} & \big| & b_{1} \\
a_{20} & a_{21} & a_{22} & \big| & b_{2}
\end{bmatrix}
$
$-->
\begin{bmatrix}
1 & 0 & 0 & \big| & b_{0}' \\
0 & 1 & 0 & \big| & b_{1}' \\
0 & 0 & 1 & \big| & b_{2}'
\end{bmatrix}
$


$a_{00}x_{0}+a_{01}x_{1}+a_{02}x_{2}=b_{0} $

$a_{10}x_{0}+a_{11}x_{1}+a_{12}x_{2}=b_{1} $

$a_{20}x_{0}+a_{21}x_{1}+a_{22}x_{2}=b_{2} $



## Row operations

After applyting first set of operations we get our matrix in the form

$R_{1} --> R_{1}/a_{00}   |$ 

$R_{2} --> R_{2}-a_{10}R_{1} |$ 

$R_{3} -->R_{3}-a_{20}R_{1} |$


 $
\begin{bmatrix}
1 & a_{01} & a_{02}   \\
0 & a_{11} & a_{12}  \\
0 & a_{21} & a_{22} 
\end{bmatrix}
$

After applying second set of operations we got our matrix in the form 

$R_{2} --> R_{2}/a_{11}   |$

$R_{1} --> R_{1}-a_{01}R_{2} |$

$R_{3} -->R_{3}-a_{21}R_{2} |$

$
\begin{bmatrix}
1 & 0 & a_{02}   \\
0 & 1 & a_{12}  \\
0 & 0 & a_{22} 
\end{bmatrix}
$

After applying third set of  operations we got our matrix in the form

$R_{3} --> R_{3}/a_{22}   |$

$R_{2} --> R_{2}-a_{12}R_{3} |$

$R_{1} -->R_{1}-a_{02}R_{3}$

$
\begin{bmatrix}
1 & 0 & 0   \\
0 & 1 & 0  \\
0 & 0 & 1 
\end{bmatrix}
$

In [1]:
from numpy import *
#from sympy import *
#init_printing()
a=array([[10,1,1],[1,10,-1],[1,-2,10]],float)
b=array([[12],[10],[9]],float)
print(a,",")
m1=a[0,0]
print("m1 is",m1)
a[0,:]=a[0,:]/m1 # R1=R1/10
b[0,:]=b[0,:]/m1 
print(a,",")

m2=a[1,0]
print("m2 is",m2)
a[1,:]=a[1,:]-m2*a[0,:] #R2=R2-(1)R1 
b[1,:]=b[1,:]-m2*b[0,:]
print(a,",")

m2=a[2,0]
print("m2 is",m2)
a[2,:]=a[2,:]-m2*a[0,:] #R3=R3-(1)R1
b[2,:]=b[2,:]-m2*b[0,:]
print(a,",")

m1=a[1,1]
print("m1 is",m1)
a[1,:]=a[1,:]/m1 #R2=R2/9.9
b[1,:]=b[1,:]/m1
print(a,",")

m2=a[0,1]
print("m2 is",m2)
a[0,:]=a[0,:]-m2*a[1,:] #R1=R1-(0.1)R2
b[0,:]=b[0,:]-m2*b[1,:]
print(a,",")

m2=a[2,1]
print("m2 is",m2)
a[2,:]=a[2,:]-m2*a[1,:] #R3=R3-(-2.1)R2
b[2,:]=b[2,:]-m2*b[1,:]
print(a,",")

m1=a[2,2]
print("m1 is",m1)
a[2,:]=a[2,:]/m1 #R3=R3/9.66
b[2,:]=b[2,:]/m1
print(a,",")

m2=a[1,2]
print("m2 is",m2)

a[1,:]=a[1,:]-m2*a[2,:] #R2=R2-(-0.11)R3
b[1,:]=b[1,:]-m2*b[2,:]
print(a,",")

m2=a[0,2]
print("m2 is",m2)

a[0,:]=a[0,:]-m2*a[2,:] #R1=R1-(0.11)R3
b[0,:]=b[0,:]-m2*b[2,:]
print(a,",")
print(b)

[[10.  1.  1.]
 [ 1. 10. -1.]
 [ 1. -2. 10.]] ,
m1 is 10.0
[[ 1.   0.1  0.1]
 [ 1.  10.  -1. ]
 [ 1.  -2.  10. ]] ,
m2 is 1.0
[[ 1.   0.1  0.1]
 [ 0.   9.9 -1.1]
 [ 1.  -2.  10. ]] ,
m2 is 1.0
[[ 1.   0.1  0.1]
 [ 0.   9.9 -1.1]
 [ 0.  -2.1  9.9]] ,
m1 is 9.9
[[ 1.          0.1         0.1       ]
 [ 0.          1.         -0.11111111]
 [ 0.         -2.1         9.9       ]] ,
m2 is 0.1
[[ 1.          0.          0.11111111]
 [ 0.          1.         -0.11111111]
 [ 0.         -2.1         9.9       ]] ,
m2 is -2.1
[[ 1.          0.          0.11111111]
 [ 0.          1.         -0.11111111]
 [ 0.          0.          9.66666667]] ,
m1 is 9.666666666666668
[[ 1.          0.          0.11111111]
 [ 0.          1.         -0.11111111]
 [ 0.          0.          1.        ]] ,
m2 is -0.11111111111111112
[[1.         0.         0.11111111]
 [0.         1.         0.        ]
 [0.         0.         1.        ]] ,
m2 is 0.11111111111111112
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] ,
[[1.]
 [1.]


In [3]:
from numpy import *
a=array([[10,1,1],[1,10,-1],[1,-2,10]],float)
b=array([[12],[10],[9]],float)
def gaussjordan(a,b):   
    n=len(b) 
    for i in range(0,n):#i=0,1,2
        m1=a[i,i]
        a[i,:]=a[i,:]/m1
        b[i,:]=b[i,:]/m1
        for j in range(0,n):#J=0,1,2
            if j!=i:
                m2 = a[j, i]  # Storing the original value of a[j,i] in m2
                a[j, :]=a[j, :]-m2*a[i, :]
                b[j, :]=b[j, :]-m2*b[i, :]     
    for i in range(n):
        print(f"x{(i+1)} is {b[i]}")
def executiontime(func,*args):
    import time as t
    s = t.time()
    func(*args)
    e = t.time()
    print("Execution Time:", e - s, "seconds")
executiontime(gaussjordan,a,b)

x1 is [1.]
x2 is [1.]
x3 is [1.]
Execution Time: 0.0 seconds


## If solution does not exist 
Q.Solve the following equations using gauss jordan method.

$2x-4y+z=-4$

$4x-8y+7z=2$

$-2x+4y-3z=5$


In [4]:
from numpy import *
a = array([[2,-4,1],[4,-8,7],[-2,4,-3]],float)
b = array([[-4],[2],[5]],float)
gaussjordan(a,b)

x1 is [nan]
x2 is [nan]
x3 is [nan]


C:\Users\kotil\AppData\Local\Temp\ipykernel_20668\2029172795.py:8: RuntimeWarning: divide by zero encountered in divide
  a[i,:]=a[i,:]/m1
C:\Users\kotil\AppData\Local\Temp\ipykernel_20668\2029172795.py:8: RuntimeWarning: invalid value encountered in divide
  a[i,:]=a[i,:]/m1
C:\Users\kotil\AppData\Local\Temp\ipykernel_20668\2029172795.py:9: RuntimeWarning: divide by zero encountered in divide
  b[i,:]=b[i,:]/m1
C:\Users\kotil\AppData\Local\Temp\ipykernel_20668\2029172795.py:13: RuntimeWarning: invalid value encountered in multiply
  a[j, :]=a[j, :]-m2*a[i, :]
C:\Users\kotil\AppData\Local\Temp\ipykernel_20668\2029172795.py:14: RuntimeWarning: invalid value encountered in multiply
  b[j, :]=b[j, :]-m2*b[i, :]


# Solving system of 5 equations using Gauss Jordan Method


Q.Solve the given system of equations using Gauss Jordan elimination method.

$$a+b+c+d+0=5$$

$$0+b+c+d+e=1$$

$$a+0+c+d+e=2$$

$$a+b+0+d+e=0$$

$$a+b+c+0+e=4$$

## Solution 
$$a=2$$ $$b=1$$ $$c=3$$ $$d=-1$$ $$e=-2$$


In [5]:
from numpy import *
a = array([[1,1,1,1,0],[0,1,1,1,1],[1,0,1,1,1],[1,1,0,1,1],[1,1,1,0,1]],float)
b = array([[5],[1],[2],[0],[4]],float)
executiontime(gaussjordan,a,b)

x1 is [2.]
x2 is [1.]
x3 is [3.]
x4 is [-1.]
x5 is [-2.]
Execution Time: 0.0 seconds


In [6]:
a=array([[2, 1, -3, 4, 0, 1, 2, 0, -1, 3],
              [-1, 2, 0, 3, 2, 0, -1, 4, -3, 2],
              [0, 3, 1, -1, 2, 3, 1, 2, -2, 1],
              [4, 0, 2, 1, -3, 2, 0, 1, 3, -1],
              [1, -1, 2, 0, 4, -1, 2, 3, 0, 1],
              [3, 2, 3, 2, 0, 1, -3, 1, 2, 0],
              [-2, 1, 0, 3, 1, 2, 4, -1, -2, 3],
              [0, 4, 2, 0, 3, 3, 1, -1, 2, 0],
              [-3, 0, -2, 1, 0, 2, -2, 3, 1, 2],
              [1, 3, 1, -2, 1, 0, 3, 0, 4, -1]])

b = array([[8],
              [9],
              [5],
              [3],
              [10],
              [6],
              [2],
              [7],
              [1],
              [4]], float)
executiontime(gaussjordan,a,b)

x1 is [-6.1321978]
x2 is [7.52016484]
x3 is [-15.01782967]
x4 is [2.11428571]
x5 is [1.46489011]
x6 is [1.47521978]
x7 is [-1.00521978]
x8 is [0.73016484]
x9 is [0.06497253]
x10 is [-8.10898352]
Execution Time: 0.008485555648803711 seconds


## Solving system of 20 equations in 20 variables 

In [7]:
a=array([[2, 1, -3, 4, 0, 1, 2, 0, -1, 3, 0, 2, -1, 3, 1, 2, -2, 1, 0, -2],
              [-1, 2, 0, 3, 2, 0, -1, 4, -3, 2, 3, 1, -1, 2, 0, 1, 3, -1, 0, 4],
              [0, 3, 1, -1, 2, 3, 1, 2, -2, 1, 1, 2, 0, 4, -1, 2, 3, 0, 2, -3],
              [4, 0, 2, 1, -3, 2, 0, 1, 3, -1, 3, 2, 3, 2, 0, 1, -3, 1, 2, 0],
              [1, -1, 2, 0, 4, -1, 2, 3, 0, 1, -2, 1, 0, 3, 2, 3, 2, 0, 1, -3],
              [3, 2, 3, 2, 0, 1, -3, 1, 2, 0, 0, 3, 1, 2, 4, -1, -2, 3, 0, 4],
              [-2, 1, 0, 3, 1, 2, 4, -1, -2, 3, 2, 0, 1, 3, 1, 2, -2, 1, 0, -2],
              [0, 4, 2, 0, 3, 3, 1, -1, 2, 0, 3, 1, -1, 2, 0, 1, 3, -1, 0, 4],
              [-3, 0, -2, 1, 0, 2, -2, 3, 1, 2, 1, -1, 2, 0, 4, -1, -2, 3, 0, 2],
              [1, 3, 1, -2, 1, 0, 3, 0, 4, -1, 2, 0, 3, 2, 3, 2, 0, 1, -3, 1],
              [0, 2, -1, 3, 1, 2, -2, 1, 0, -2, 2, 1, -3, 4, 0, 1, 2, 0, -1, 3],
              [-1, 2, 0, 3, 2, 0, -1, 4, -3, 2, 0, 3, 1, -1, 2, 0, 1, 3, -1, 0],
              [2, 0, 1, 3, 2, 0, 1, -1, -2, 3, 2, 0, 1, 3, 2, 0, 1, -3, 1, 2],
              [0, 1, -3, 4, 0, 1, 2, 0, -1, 3, 0, 2, -1, 3, 1, 2, -2, 1, 0, -2],
              [-1, 2, 7, 3, 2, 5, -1, 4, -3, 2, 3, 1, -1, 2, 3, 1, 3, -1, 5, 4],
              [4, 3, 1, -1, 2, 3, 1, 2, -2, 1, 1, 2, 3, 4, -1, 2, 3, 2, 2, -3],
              [4, 4, 2, 1, -3, 2, 2, 1, 3, -1, 3, 2, 3, 2, 3, 1, -3, 1, 2, 5],
              [1, -1, 2, 1, 4, -1, 2, 3, 3, 1, -2, 1, 4, 3, 2, 3, 2, 3, 1, -3],
              [3, 2, 3, 2, 9, 1, -3, 1, 2, 7, 2, 3, 1, 2, 4, -1, -2, 3, 4, 4],
              [-2, 1, 4, 3, 1, 2, 4, -1, -2, 3, 2, 4, 1, 3, 1, 2, -2, 1, 5, -2],
              [0, 4, 2, 3, 3, 3, 1, -1, 2, 2, 3, 1, -1, 2, 1, 1, 3, -1, 1, 4]],float)
b = array([[8],[9],[5],[3],[10],[6],[2],[7],[1],[4],[2],[3],[1],[4],[2],[3],[1],[4],[2], [3]], float)
def executiontime(func,*args):
    import time as t
    s = t.time()
    func(*args)
    e = t.time()
    print("Execution Time:", e - s, "seconds")
executiontime(gaussjordan,a,b)

x1 is [2.]
x2 is [-6.00808835]
x3 is [1.40859021]
x4 is [-2.4358539]
x5 is [-2.70339437]
x6 is [0.83085972]
x7 is [10.06175697]
x8 is [5.43809765]
x9 is [2.70548913]
x10 is [4.17911079]
x11 is [2.35781984]
x12 is [3.10355536]
x13 is [-6.638773]
x14 is [4.39278723]
x15 is [-1.32194927]
x16 is [-13.18102446]
x17 is [3.87873705]
x18 is [4.9581595]
x19 is [-3.40971646]
x20 is [1.17493745]
Execution Time: 0.00921487808227539 seconds
