# Matrix 
$
\begin{bmatrix}
a_{00} & a_{01} & a_{02} \\
a_{10} & a_{11} & a_{12} \\
a_{20} & a_{21} & a_{22}
\end{bmatrix}
$

## Creating a matrix

In [2]:
from numpy import *
a=array([[1, 2], [3, 4]],float)
b=array([[3,1], [5,6]],float)
print(a,",")
print(b)

[[1. 2.]
 [3. 4.]] ,
[[3. 1.]
 [5. 6.]]


## Matrix addition

In [3]:
c=a+b
print(c)

[[ 4.  3.]
 [ 8. 10.]]


## Matrix subtraction 

In [4]:
d=b-a
print(d)

[[ 2. -1.]
 [ 2.  2.]]


## Matrix multiplication 

In [5]:
e=dot(a,b) # dot function to multipy matrices
print(e)

[[13. 13.]
 [29. 27.]]


## Scalar matrix multiplication

In [6]:
f=3*a # multiplying matrix a with 2 
print(f)

[[ 3.  6.]
 [ 9. 12.]]


## Matrix Transpose

In [7]:
G=a.T
print(G)

[[1. 3.]
 [2. 4.]]


## Inverse of a matrix
- Here we will use linalg.inv() , function to invert a matrix.
<div class="alert alert-block alert-danger">
<b>Note:</b> It can only be used for square matices.If you want to find inverse of a non square matrix use "linalg.pinv()" method.
</div>


In [8]:
A=array([[2,-3,5], [6,0,4], [1,5,-7]])
H=linalg.inv(A)
print(A)
print(H)

[[ 2 -3  5]
 [ 6  0  4]
 [ 1  5 -7]]
[[ 0.71428571 -0.14285714  0.42857143]
 [-1.64285714  0.67857143 -0.78571429]
 [-1.07142857  0.46428571 -0.64285714]]


## Determinant 

In [9]:
det=linalg.det(a)
print(a,det)

[[1. 2.]
 [3. 4.]] -2.0000000000000004


## Inverse Matrix method of solving equation
 
$a_{1}x+b_{1}y+c_{1}z=d1$

$a_{2}x+b_{2}y+c_{2}z=d2$

$a_{3}x+b_{3}y+c_{3}z=d3$

    
$A=
\begin{bmatrix}
a_{1} & b_{1} & c_{1} \\
a_{2} & b_{2} & c_{2} \\
a_{3} & b_{3} & c_{3}
\end{bmatrix}$,
$X=
\begin{bmatrix}
x \\
y \\
z
\end{bmatrix}$,
$B=
\begin{bmatrix}
d_{1} \\
d_{2}\\
d_{3}
\end{bmatrix}$

We can represent the above equations in the form 

$\begin{bmatrix}
a_{1} & b_{1} & c_{1} \\
a_{2} & b_{2} & c_{2} \\
a_{3} & b_{3} & c_{3}
\end{bmatrix}$
$\begin{bmatrix}
x \\
y \\
z
\end{bmatrix}=
\begin{bmatrix}
d_{1} \\
d_{2}\\
d_{3}
\end{bmatrix}$


$AX=B$


$X=A^{-1}B$



Q1.Solve following equations using inverse matrix method.
   - $2x+5y=1$
   - $3x+2y=7$
### Solution 
$x=3$, $y=-1$

In [16]:
from numpy import *
A=array([[2,5],[3,2]]) 
B=array([[1],[7]])
inv_A=linalg.inv(A) # taking inverse of A
solution=dot(inv_A,B) # multiplying A inverse and B
#print(A)
print(solution)

[[ 3.]
 [-1.]]


Q1.Solve following equations using inverse matrix method.
   - $2x+y+z=10$
   - $3x+2y+3z=18$
   - $x+4y+9z=16$
### Solution 
$x=7$,
$y=-9$,
$z=5$

In [19]:
a=array([[2,1,1],[3,2,3],[1,4,9]])
b=array([[10],[18],[16]])
inv_a=linalg.inv(a) # taking inverse of A
solution=dot(inv_a,b) # multiplying A inverse and B
print(solution)

[[ 7.]
 [-9.]
 [ 5.]]


## Guass Elimination 
Q1.Solve the system of equations using gauss elimniation method

In [12]:
a=array([[2,1,1],[3,2,3],[1,4,9]],float)
b=array([[10],[18],[16]],float)
n=len(b) #n=3
for i in range(0,n-1):
    m1=a[i,i]
    print(m1)
    a[i,:]=a[i,:]/m1
    b[i]=b[i]/m1
    print(a,",")
    for j in range (i+1,n):
        m2=a[j,i]
        a[j,:]=a[j,:]-m2*a[i,:]
        b[j]=b[j]-m2*b[i]
        print(a,",")
a

2.0
[[1.  0.5 0.5]
 [3.  2.  3. ]
 [1.  4.  9. ]] ,
[[1.  0.5 0.5]
 [0.  0.5 1.5]
 [1.  4.  9. ]] ,
[[1.  0.5 0.5]
 [0.  0.5 1.5]
 [0.  3.5 8.5]] ,
0.5
[[1.  0.5 0.5]
 [0.  1.  3. ]
 [0.  3.5 8.5]] ,
[[ 1.   0.5  0.5]
 [ 0.   1.   3. ]
 [ 0.   0.  -2. ]] ,


array([[ 1. ,  0.5,  0.5],
       [ 0. ,  1. ,  3. ],
       [ 0. ,  0. , -2. ]])

In [13]:
b

array([[  5.],
       [  6.],
       [-10.]])

## Back substitution 

This is the formula we are using here
- $$x_i = \frac{{b_i - \sum_{{j=i+1}}^n{{a_{{ij}}  x_j}}}}{{a_{{ii}}}}$$



In [14]:
import numpy as np
#a = np.array([[1.0, 0.5, 0.5], [0.0, 1.0, 3.0], [0.0, 0.0, -2.0]])
#b = np.array([5, 6, -10],float)
n = len(b)  # n=3
x = np.zeros(n) # it creates an array [[0,0,0]]
print(x)
for i in range(n - 1, -1, -1): # i=2,1,0
    x[i] = b[i]
    print(x,",")
    for j in range(i + 1, n):
        x[i] -= a[i, j] * x[j]
        print(x,",")
    x[i] /= a[i, i]
    print(x)

print("Solution Vector x:")
print(x)

[0. 0. 0.]
[  0.   0. -10.] ,
[0. 0. 5.]
[0. 6. 5.] ,
[ 0. -9.  5.] ,
[ 0. -9.  5.]
[ 5. -9.  5.] ,
[ 9.5 -9.   5. ] ,
[ 7. -9.  5.] ,
[ 7. -9.  5.]
Solution Vector x:
[ 7. -9.  5.]
